### PR TITLE
viz: directly create vector graphics to display vg data models in SVG

### PR DESCRIPTION
**Pull request by ekg**
This PR implements a new visualization model that directly uses libcairo, the xg and the pack coverage index to develop a linear-time vector based rendering model.

You use it like this:

```
vg construct -r tiny/tiny.fa -v tiny/tiny.vcf.gz >t.vg
vg index -x t.xg -g t.gcsa t.vg
vg map -G <(vg sim -l 30 -n 100 -x t.xg -a) -d t | vg pack -x t.xg -o t.cx -g -
vg viz -x t.xg -o t.svg -i t.cx -n alignments
```

image

I've enjoyed applying it to the HLA test graphs:

image

The core idea is that we use the linearization of the graph that's baked into XG. The SVG output does not require much memory, but it does take a lot of memory to load. It would be ideal if we could set up something like "deep zoomable images" (DZI) on top of the output. I'm trying to learn how to do this.

A different kind of hack would be to render in chunks, then load the chunks one by one in a browser, adding some kind of hyperlinks to the sides of the view and the edges so that we can jump left and right and also follow edges interactively.

### CODE REVIEW

**Comment by ekg** [comment]
Todo:

- [ ] show alignment sequences (ala tview)
- [ ] figure out how to rasterize or display whole chromosomes (limited by viewer)
- [ ] indicate the orientation of reference paths and alignment paths using the IGV motif of a triangular end in the direction of the read
- [ ] determine how to normalize coverages so that it's clear when a given node is at half or double copy relative to its neighbors (this is relevant also for analysis of coverage maps / packs over the graph)
- [ ] show variant calls
- [ ] show haplotype counts on edges or GBWT haplotypes as paths
- [ ] show the node numbers and or path offsets (chr:pos) to make interpretation easier

**Comment by ekg** [comment]
I'm struggling to get the osx build to work. It keeps throwing up errors as it is apparently impossible to use pkg-config to get the CFLAGS and libs for GCC when the libraries have been installed with brew. Does anyone with a Mac have insight?

**Comment by ekg** [comment]
Jenkins, test this please.

**Comment by ekg** [comment]
This should only affect the build, and only adds the viz command. Committing because Travis is happy-ish. Jenkins is ignoring me.

**Comment by glennhickey** [comment]
@ekg it seems you broke the jenkins build, actually

checking for library containing lzma_auto_decoder... make[3]: Entering directory '/vg/deps/raptor/build'
make[3]: Entering directory '/vg/deps/raptor/build'
[ 64%] Building C object src/CMakeFiles/raptor_snprintf_test.dir/snprintf.c.o
[ 65%] Building C object src/CMakeFiles/raptor_sort_r_test.dir/sort_r.c.o
yes
checking for memset... [ 65%] Linking C executable raptor_sort_r_test
[ 66%] Linking C executable raptor_snprintf_test
ar rs libvcflib.a src/Variant.o src/rnglib.o src/var.o src/pdflib.o src/cdflib.o src/split.o smithwaterman/sw.o fastahack/Fasta.o src/ssw.o src/ssw_cpp.o filevercmp/filevercmp.o tabixpp/tabix.o
[91mar: creating libvcflib.a
[0m[91mlibraptor2.a(turtle_parser.c.o): In function `turtle_parser_parse':
turtle_parser.c:(.text+0xb08): undefined reference to `turtle_lexer_lex'
libraptor2.a(turtle_parser.c.o): In function `turtle_parse':
turtle_parser.c:(.text+0x3496): undefined reference to `turtle_lexer_lex_init'
turtle_parser.c:(.text+0x34c3): undefined reference to `turtle_lexer_set_extra'
turtle_parser.c:(.text+0x34e1): undefined reference to `turtle_lexer__scan_bytes'
turtle_parser.c:(.text+0x350b): undefined reference to `turtle_lexer_lex_destroy'
libraptor2.a(turtle_parser.c.o): In function `raptor_turtle_parse_terminate':
turtle_parser.c:(.text+0x35d4): undefined reference to `turtle_lexer_lex_destroy'
collect2: error: ld returned 1 exit status
[0msrc/CMakeFiles/raptor_sort_r_test.dir/build.make:96: recipe for target 'src/raptor_sort_r_test' failed
make[3]: Leaving directory '/vg/deps/raptor/build'
CMakeFiles/Makefile2:127: recipe for target 'src/CMakeFiles/raptor_sort_r_test.dir/all' failed
[91mmake[3]: *** [src/raptor_sort_r_test] Error 1
make[2]: *** [src/CMakeFiles/raptor_sort_r_test.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[0mcat deps/DYNAMIC/include/dynamic.hpp | sed 's%<internal/%<dynamic/%' >include/dynamic.hpp && cp -r /vg/deps/DYNAMIC/include/internal /vg/include/dynamic
cp libvcflib.a lib
make[1]: Leaving directory '/vg/deps/vcflib'
mv ../bin/sonLib_cigarTest.tmp ../bin/sonLib_cigarTest
cd deps/sparsehash && ./autogen.sh && LDFLAGS="-L/opt/local/lib" ./configure --prefix=/vg  && make  && make install
-llzma

**Comment by ekg** [comment]
@JervenBolleman can we consider getting rid of raptor? @glennhickey I'll have to dig into this. It looks like what I did to make raptor build on ubuntu 18.04 killed the build.

**Comment by glennhickey** [comment]
Cool.  Fixing this should also fix vg_docker which has the same issue
https://api.travis-ci.org/v3/job/376527446/log.txt

**Comment by JervenBolleman** [comment]
@ekg You can do what you want but it would be nice if you would at least help with the JSON-LD'ification of the VG JSON (#1556). As some breaking changes where put in recently in the existing VG json by @adamnovak that where needed for JSON-LD. it would be nice if someone could look at this. Because removing all RDF support would really break my work and make me sad...

**Comment by JervenBolleman** [comment]
Also if you are now on a modern ubuntu you can probably use the packaged librdf/raptor and no longer build it from source.

**Comment by glennhickey** [comment]
I get the same error as the Docker builds on fresh clones of vg on both
Ubuntu 16.04 and 18.04.  @ekg I suspect you can reproduce it locally on a
fresh checkout too.

**Comment by JervenBolleman** [comment]
@glennhickey @ekg doing a branch to test building with a system raptor instead of an in three one.
