### ISSUE TITLE
VG does not build on Ubuntu 14.04 LTS fresh from the factory

### ISSUE THREAD

**Issue by JervenBolleman** [vgteam/vg#639]
Got myself a new toy for VG development. Immediatly got this error
```
g++ -c -o src/Variant.o src/Variant.cpp -Itabixpp/htslib -Iinclude -L. -Ltabixpp/htslib -Llib -lvcflib -lhts -lpthread -lz -lm -O3 -D_FILE_OFFSET_BITS=64 -std=c++0x && cp src/*.h* /home/jbollema/git/vg/deps/vcflib/include/
src/Variant.cpp: In member function ‘bool vcflib::Variant::canonicalize_sv(FastaReference&, std::vector<FastaReference*>, int)’:
src/Variant.cpp:182:95: error: no matching function for call to ‘regex_replace(__gnu_cxx::__alloc_traits<std::allocator<std::basic_string<char> > >::value_type&, std::regex&, const char [1])’
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
src/Variant.cpp:182:95: note: candidates are:
In file included from /usr/include/c++/4.8/regex:62:0,
                 from src/Variant.h:18,
                 from src/Variant.cpp:1:
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
src/Variant.cpp:182:95: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
In file included from /usr/include/c++/4.8/regex:62:0,
                 from src/Variant.h:18,
                 from src/Variant.cpp:1:
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
src/Variant.cpp:182:95: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
                                 string var_name = regex_replace(this->alt[alt_pos], arrows, "");
                                                                                               ^
make[1]: *** [src/Variant.o] Error 1
```

**Comment by adamnovak** [comment]
You're building with GCC 4.8, which does not implement `std::regex`. You need GCC 4.9 or higher.

Try this:

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9
```

**Comment by JervenBolleman** [comment]
@adamnovak that was a real duh moment of mine! thanks for spotting it!
