### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by egafni** [vgteam/vg#415]
I've had a lot of problems getting vg to compile on ubuntu 14.04, here's the error message.  Any help would be appreciated!

 ./source_me.sh && g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -c -o obj/main.o src/main.cpp -I/locus/home/egafni/tools/vg/include -I. -I/locus/home/egafni/tools/vg/src -I/locus/home/egafni/tools/vg/cpp -I/locus/home/egafni/tools/vg/include/dynamic -I/locus/home/egafni/tools/vg/include/sonLib -ggdb -L/locus/home/egafni/tools/vg/lib -lvcflib -lgssw -lssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lxg -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -lsupbub -lsdsl -lpinchesandcacti -l3edgeconnected  -lsonlib -lrt
. ./source_me.sh && g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -o bin/vg obj/main.o -lvg -I/locus/home/egafni/tools/vg/include -I. -I/locus/home/egafni/tools/vg/src -I/locus/home/egafni/tools/vg/cpp -I/locus/home/egafni/tools/vg/include/dynamic -I/locus/home/egafni/tools/vg/include/sonLib -ggdb -L/locus/home/egafni/tools/vg/lib -lvcflib -lgssw -lssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2 -lgcsa2 -lxg -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -lsupbub -lsdsl -lpinchesandcacti -l3edgeconnected  -lsonlib -lrt
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `vg::Pileups::parse_delete(std::string const&, bool&, long&, long&, bool&, long&, long&, bool&)':
/locus/home/egafni/tools/vg/src/pileup.cpp:719: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator()'
/locus/home/egafni/tools/vg/src/pileup.cpp:719: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, int, std::bitset<11ul>)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `copy<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > >, std::back_insert_iterator<std::vector<std::basic_string<char> > > >':
/usr/include/c++/4.8/bits/stl_algobase.h:460: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `__miter_base<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > > >':
/usr/include/c++/4.8/bits/stl_algobase.h:289: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `std::_Iter_base<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >, false>::_S_base(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >)':
/usr/include/c++/4.8/bits/stl_iterator_base_types.h:213: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `copy<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > >, std::back_insert_iterator<std::vector<std::basic_string<char> > > >':
/usr/include/c++/4.8/bits/stl_algobase.h:460: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `__miter_base<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > > >':
/usr/include/c++/4.8/bits/stl_algobase.h:289: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o):/usr/include/c++/4.8/bits/stl_iterator_base_types.h:213: more undefined references to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_token_iterator(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)' follow
/locus/home/egafni/tools/vg/lib/libvg.a(pileup.o): In function `__copy_m<std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::basic_string<char> > >, std::back_insert_iterator<std::vector<std::basic_string<char> > > >':
/usr/include/c++/4.8/bits/stl_algobase.h:304: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
/usr/include/c++/4.8/bits/stl_algobase.h:304: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
/usr/include/c++/4.8/bits/stl_algobase.h:305: undefined reference to `std::regex_token_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator*()'
collect2: error: ld returned 1 exit status
make: *** [bin/vg] Error 1

**Comment by pgrosu** [comment]
Hi Erik,

Try using gcc 4.9 instead of 4.8 based on the following issue:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57513

~p

**Comment by adamnovak** [comment]
Using gcc 4.8 is definitely the problem. It's not supported because it doesn't provide implementations for `std::regex`, part of C++11. It does provide the headers, though, which is why builds with gcc 4.8 weirdly fail at link time.

**Comment by adamnovak** [comment]
We should update the documentation (or Makefile?) to be more clear that gcc 4.8 will not work.

**Comment by egafni** [comment]
gcc 4.9 fixed the problem, thanks!  I'm sure other people are running into this so updating the README would be great.

**Comment by ekg** [comment]
I've added a line to my local README to describe this, but it may be a day
or so before I get a chance to push it up.

**Comment by adamnovak** [comment]
I'm going to close this, since the problem has been solved.

**Comment by JPacho** [comment]
Using gcc 4.9 or greater instead of 4.8.3 solves this issue.
https://github.com/raspberrypi/tools
