### ISSUE TITLE
Compile fail on Ubuntu 16.04: vg_git_version.hpp missing

### ISSUE THREAD

**Issue by NickSto** [vgteam/vg#614]
Hi, so I just got a new laptop with Ubuntu 16.04 on it, and I was thinking maybe now I'll finally have the right dependencies to build vg!

So first I tried installing all the packages recommended by the README:
`$ sudo apt install build-essential git cmake pkg-config libncurses-dev libbz2-dev protobuf-compiler libprotoc-dev libjansson-dev automake libtool jq bc curl unzip redland-utils librdf-dev bison flex`
Some of the package names (`libncurses-dev` and `librdf-dev`) didn't match exactly those in the repositories, so here's what actually got installed:
```
build-essential:    12.1ubuntu2
git:                1:2.7.4-0ubuntu1
cmake:              3.5.1-1ubuntu3
pkg-config:         0.29.1-0ubuntu1
libncurses5-dev:    6.0+20160213-1ubuntu1
libbz2-dev:         1.0.6-8
protobuf-compiler:  2.6.1-1.3
libprotoc-dev:      2.6.1-1.3
libjansson-dev:     2.7-3
automake:           1:1.15-4ubuntu1
libtool:            2.4.6-0.1
jq:                 1.5+dfsg-1
bc:                 1.06.95-9build1
curl:               7.47.0-1ubuntu2.2
unzip:              6.0-20ubuntu1
redland-utils:      1.0.17-1build1
librdf0-dev:        1.0.17-1build1
bison:              2:3.0.4.dfsg-1
flex:               2.6.0-11
```

Then I cloned a fresh copy of vg (commit `b7df129`), and compiled:
```bash
$ git clone --recursive git@github.com:vgteam/vg.git
$ cd vg
$ source source_me.sh
$ make static
```

But it failed. The last 10 lines of output:
```
 /bin/mkdir -p '/home/me/bx/src/vg/deps/gperftools/lib/pkgconfig'
 /usr/bin/install -c -m 644 libtcmalloc.pc libtcmalloc_minimal.pc libtcmalloc_debug.pc libtcmalloc_minimal_debug.pc libprofiler.pc '/home/me/bx/src/vg/deps/gperftools/lib/pkgconfig'
make[2]: Leaving directory '/home/me/annex/Work/PSU/Nekrutenko/src/vg/deps/gperftools'
make[1]: Leaving directory '/home/me/annex/Work/PSU/Nekrutenko/src/vg/deps/gperftools'
. ./source_me.sh && g++ -O3 -msse4.1 -fopenmp -std=c++11 -ggdb -g -c -o obj/main.o src/main.cpp -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/include -I. -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/src -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/src/unittest -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/src/subcommand -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/cpp -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/include/dynamic -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/include/sonLib -I/home/me/annex/Work/PSU/Nekrutenko/src/vg/include/gcsa -ggdb -L/home/me/annex/Work/PSU/Nekrutenko/src/vg/lib -lvcflib -lgssw -lssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lgcsa2 -lxg -ldivsufsort -ldivsufsort64 -lvcfh -lgfakluge -lraptor2 -lsupbub -lsdsl -lpinchesandcacti -l3edgeconnected -lsonlib  -Wl,-rpath,/home/me/annex/Work/PSU/Nekrutenko/src/vg/lib -lrocksdb  -lpthread -lrt -lsnappy -lz -lbz2
In file included from src/main.cpp:32:0:
/home/me/annex/Work/PSU/Nekrutenko/src/vg/src/subcommand/homogenize_main.cpp:25:30: fatal error: vg_git_version.hpp: No such file or directory
compilation terminated.
Makefile:460: recipe for target 'obj/main.o' failed
make: *** [obj/main.o] Error 1
```

There is indeed no `vg_git_version.hpp` anywhere in the source. I remember an issue with this file earlier (#503), but I'm not sure how/if this is related. In any case, that fix didn't seem to take care of this.

I really thought it should work on a new install of 16.04, but I don't know what's wrong.

`uname -a`: `Linux ruby 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ekg** [comment]
It definitely should work on a new Ubuntu 16.04. The problem isn't system level though, it looks like an issue with the build.

vg_git_version.hpp is generated by the Makefile:

```
-> % grep -A 1 vg_git_version.hpp Makefile
$(INC_DIR)/vg_git_version.hpp: #.git
        echo "#define VG_GIT_VERSION \"$(shell git describe --always --tags || echo unknown)\"" > $@
```

Try `make include/vg_git_version.hpp`, then `make static`.

Now, if that works I'm still confused about how this happened.

**Comment by NickSto** [comment]
Yeah, I looked at the line in the Makefile later and executed it myself, and it all worked fine.

And now I tried what you suggest:
```bash
$ make include/vg_git_version.hpp
$ cat include/vg_git_version.hpp 
#define VG_GIT_VERSION "v1.4.0-1896-gb7df129"
$ make static
```
And this time, it worked! So yeah, I really don't know what's going on.

**Comment by ekg** [comment]
My guess is some kind of dependency misspecification.
